# Generated by Django 4.1.5 on 2023-01-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='position',
            field=models.CharField(choices=[('ART', 'статья'), ('NEW', 'новость')], default='-', max_length=3),
        ),
    ]
